### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by amarsahinovic** [Pistos/diakonos#22]
As soon as I try to open a file with Ctrl+O, i get "ArgumentError: invalid byte sequence in UTF-8", full details here http://pastebin.com/bGuAKn8K

Arch Linux 64bit, Diakonos 0.9.0

**Comment by shevegen** [comment]
What encoding have you been using?

"M�m - Green Grass of Tunnel .mp3"

is displayed in a strange way here for me. Is this UTF-8?

**Comment by Pistos** [comment]
Closing this due to age.  If you still have issues, please respond, and we can reopen this issue.
