### ISSUE TITLE
Timeout for long-running regexp searches (grep, find, etc.)

### ISSUE THREAD

**Issue by Pistos** [Pistos/diakonos#37]
This is so that it doesn't lock up the interface.  For example, this is often triggered when you use `|` in greps.

**Comment by Pistos** [comment]
This feature request will be obviated when https://github.com/Pistos/diakonos/issues/61 is completed.

**Comment by xtronics** [comment]
diakonos was just dropped from Debian unstable

See https://packages.qa.debian.org/d/diakonos.html



-- 
--------------------------------------------------------------------------------
Link to our website and get free US-48 shipping on your next order.

Karl Schmidt                                  EMail Karl@xtronics.com
Transtronics, Inc.                              WEB https://secure.transtronics.com
3209 West 9th Street                             Ph (785) 841-3089
Lawrence, KS 66049                              FAX (785) 841-3089

The society that puts equality before freedom will
end up with neither. The society that puts freedom
before equality will end up with a great measure of both.
- Milton Freidman
--------------------------------------------------------------------------------

**Comment by Pistos** [comment]
@xtronics Thanks for letting me know.
