### ISSUE TITLE
Diakonos on Windows 7 and 8

### ISSUE THREAD

**Issue by vtypal** [Pistos/diakonos#39]
I have successfully installed diakonos on windows (tested on Windows 7 and 8) using gist.github.com/vtypal/6680427

Everything works fine, but i have a problem when inserting text. For each keystroke, the first key respond normally, but the next does not respond. A solution to prevent this kind of problem would be to hold down the first key for a longer time.

I changed the sensitivity of the keyboard from my windows machine, but this keyboard sensitivity problem seems to depend on editor side (or curses side). Could you please suggest some guideline to resolve this? 

Tested on ruby 2.0.0p247 (rubyinstaller for windows)

**Comment by Pistos** [comment]
Closing due to age.  (I don't have much interest in supporting Windows compatibility.)
