### ISSUE TITLE
Improve Python syntax highlighting with triple-quoted strings

### ISSUE THREAD

**Issue by ikrase** [Pistos/diakonos#63]
Currently, the Python syntax highlighter, at least as the default conf file defines it, does not highlight triple-quoted multiline strings such as docstrings. Since multiline comments in languages like C and Java work, this has to be possible, but I haven't been able to successfully enable it. 

Can we have a Python triple-quoted string highlighter?

**Comment by Pistos** [comment]
You're right, it should be possible.  I'll have a look.

**Comment by Pistos** [comment]
@ikrase Okay, try `master` (at f71cd480eaf6e).
