### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by pepa65** [Pistos/diakonos#72]
Installed diakonos from this github repo: `sudo ruby install.rb`

> Diakonos 0.9.6 (February 19, 2016) installed.
> 
> If Diakonos has been installed with a Linux distro's package manager,
> uninstall using that package manager.
> If Diakonos has been installed independently of a package manager,
> uninstall by running:
> 
>   diakonos --uninstall
> 
> Thank you for installing Diakonos.  Have a stupendous day!  :)

The editor doesn't work, so I try to uninstall: `sudo diakonos --uninstall`
That doesn't work:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- curses (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/site_ruby/2.3.0/diakonos.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/bin/diakonos:3:in `<main>'

```

**Comment by Pistos** [comment]
@pepa65 Try the latest from the `master` branch.  You should be able to uninstall even without the curses gem.

**Comment by pepa65** [comment]
Thanks for fixing this!

**Comment by pepa65** [comment]
Thanks for fixing this!
