### ISSUE TITLE
Attempting to install Diakonos

### ISSUE THREAD

**Issue by dleigh** [Pistos/diakonos#75]
Hi,
Based on the happy news in the README that: 
diakonos runs perfectly well in userspace, such as under ~/usr

I tried (painfully) to install diakonos on my userspace in my shared hosting provider where I have shell access.  After much manual copying because of installation failures, I get this error when trying to start diakonos for the first time: 

```
dleigh@citron [~/usr/lib/ruby/site_ruby/1.8]# ruby ./diakonos.rb
grep: help/*: No such file or directory
./diakonos/display.rb:53:in `attrset': no implicit conversion from nil to integer (TypeError)
                                                                                                from ./diakonos/display.rb:53:in `initialize_display'
                                from ./diakonos.rb:273:in `start'
                                                                        from ./diakonos.rb:538
```

This was my install string: 
`ruby install.rb -v --prefix /home5/dleigh/usr --dest-dir /home5/dleigh --conf-dir /home5/dleigh/etc`

You'll note that this is 0.8.9 because it's the only version that runs under Ruby 1.8, which is what my hosting provider (o2switch) has.

So, if you're still helping with 0.8.9, I'd love to get this working as I'm royally sick of nano and just want a better ncurses editor to work with.

Thanks for any help you can give.

**Comment by Pistos** [comment]
I can certainly try to help you install Diakonos 0.8.9 with Ruby 1.8, but before (or instead of) trying that: Have you considered using rvm or rbenv to install a newer version of Ruby in your userspace (home dir subtree)?  Neither of them requires root access, either.

**Comment by dleigh** [comment]
No I have not considered that – didn’t know I could.  I’ve never used Ruby before, but I suppose I could try and do that first if you think that would be a better solution.  I WOULD appreciate getting the latest diakonos if possible.  Can you point me to a web page somewhere where I could read up on how to install Ruby in a userspace please?

Many thanks!

 

 <mailto:david@leighweb.com> DavidEmailSig

**Comment by Pistos** [comment]
Yep, read up at https://rvm.io/ .

**Comment by dleigh** [comment]
Ok, finally got back to this today.  I was making progress until I tried to use rvm to install ruby.  I know you're supporting rvm, but based on these messages, am I out of luck?  I tried for ruby 2.3, but should I try for an older version or is it the fact that rvm can't determine what kind of system I have specifically?  My hosting provider has a cPanel Ruby/Gem installation process but the most recent diakonos gem they have is 0.8.11. (they say that they get their gems from RubyForge - any chance you could put a more recent version on RubyForge?)

` rvm install 2.3
Searching for binary rubies, this might take some time.
No binary rubies available for: unknown/libc-2.12/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for unknown.
Install:
press any key to continue
Install: build-essential libreadline zlib1g libyaml libc6 libgdbm ncurses
press any key to continue
Requirements installation successful.
Installing Ruby from source to: /home5/dleigh/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0   646k      0  0:00:21  0:00:21 --:--:-- 1026k
ruby-2.3.0 - #extracting ruby-2.3.0 to /home5/dleigh/.rvm/src/ruby-2.3.0....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/62: No such file or directory
cat: /dev/fd/61: No such file or directory
ruby-2.3.0 - #configuring..
Error running './configure --prefix=/home5/dleigh/.rvm/rubies/ruby-2.3.0 --disable-install-doc --enable-shared',
showing last 15 lines of /home5/dleigh/.rvm/log/1466614384_ruby-2.3.0/configure.log
[2016-06-22 18:53:10] ./configure
current path: /home5/dleigh/.rvm/src/ruby-2.3.0
PATH=/usr/local/jdk/bin:/usr/local/jdk/bin:/usr/local/jdk/bin:/home5/dleigh/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/easy/bin:/usr/local/bin:/usr/X11R6/bin:/home5/dleigh/.rvm/bin:/home5/dleigh/bin:/usr/local/bin:/usr/X11R6/bin:/home5/dleigh/.rvm/bin:~/bin:/usr/local/bin:/usr/X11R6/bin:/home5/dleigh/.rvm/bin:~/bin
command(4): ./configure --prefix=/home5/dleigh/.rvm/rubies/ruby-2.3.0 --disable-install-doc --enable-shared
checking for ruby... /usr/bin/ruby
downloader.rb:180: private method `class_variable_set' called for Downloader:Class (NoMethodError)
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home5/dleigh/.rvm/src/ruby-2.3.0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
There has been an error while running configure. Halting the installation.
`

**Comment by Pistos** [comment]
> `no acceptable C compiler found`

@dleigh If you don't have root access, cannot install new Linux packages, have no C/C++ compiler, and cannot upgrade your Ruby version, then I think that system would not be able to support Diakonos.  Are you getting a tremendous deal with that hosting?  You may consider getting a VPS, which can be had from any number of providers, world-wide, for very affordable prices (IMO).  With a VPS, you have full root access, and can install and change almost anything on your server.

**Comment by dleigh** [comment]
I feel like it IS a good hosting situation, but it certainly is a shared hosting environment and I'm not prepared to go to a VPS right now.  I really don't NEED diakonos, but their terminal environment doesn't have mc and I don't like nano or vi/vim so diakonos looked promising (and I guess I could try version 0.8.11) to make that better.

Interestingly, their cPanel Ruby stuff indicates that 2.1 is their highest Ruby version.  Theoretically, if I can get a Ruby app running under their 2.1, what's the most recent version of diakonos that would work under Ruby 2.1?

Thanks!

**Comment by Pistos** [comment]
Ruby 2.1 should be able to run even the current `master` branch, so you should be good to go, BUT you also need the `curses` gem installed.  (2.0 has `curses` built in, the last version to have it as part of the core).

**Comment by Pistos** [comment]
Closing due to age.
