### ISSUE TITLE
Add ubuntu installation instructions to README.rdoc

### ISSUE THREAD

**Issue by d9k** [Pistos/diakonos#79]
> console text editor for the masses

Please add
```
sudo apt-get install libncurses5-dev  ruby-dev
sudo gem install curses
```

to README.rdoc

**Comment by Pistos** [comment]
Hey, @d9k .  Thanks for providing some feedback to help make Diakonos better.

It's easy for me to add this information to the README, but I wanted to ask: Did you install Diakonos from the Ubuntu package manager, or from the source instead?

**Comment by d9k** [comment]
Thank you for the answer, @Pistos!
I have ubuntu 16.04 xenial xerus and there is no way to install Diakonos with apt package manager for this os version, there still no ppa available. So yes, I had to install diakonos from source.

**Comment by d9k** [comment]
:+1:
