### ISSUE TITLE
i have a bug with ruby 

### ISSUE THREAD

**Issue by papatzis** [Pistos/diakonos#80]
i installed diakonos (an kai pisteuw oti eisai ellinas sta grafw sta agglika . if you are not greek just ignore it i don't say something nusty)  and i recieve the following message 

> diakonos
> /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- curses (LoadError)
> 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/lib/ruby/vendor_ruby/diakonos.rb:16:in `<top (required)>'
> 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/bin/diakonos:3:in `<main>'
so maybe i do somthing wrong i istalled ruby also rails is anything else i need to do 
?

**Comment by blazeeboy** [comment]
can you try to install `curses` with 
```
gem install curses
```
and then try again?

**Comment by Pistos** [comment]
@papatzis How are things with this issue?  Have you tried installing the `curses` gem?

**Comment by Pistos** [comment]
Closing due to lack of response.  If you still need help, you may re-open this issue.
