### ISSUE TITLE
Bignum and Fixnum changes

### ISSUE THREAD

**Issue by shevegen** [Pistos/diakonos#83]
/Programs/Ruby/2.4.2/lib/ruby/site_ruby/2.4.0/diakonos/core-ext/fixnum.rb:1: warning: constant ::Fixnum is deprecated

/Programs/Ruby/2.4.2/lib/ruby/site_ruby/2.4.0/diakonos/core-ext/bignum.rb:1: warning: constant ::Bignum is deprecated

Hey pistos. Not sure if you still maintain diakonos or not but just in case, perhaps there could be a change to check for Integer, I think? Please disregard if this has already been fixed, I am using the tarball release rather than the latest git version. Thanks!

**Comment by Pistos** [comment]
Thanks for reaching out, @shevegen .  I am definitely still maintaining Diakonos.  I use it every day, and want to know if anyone is running into problems.

Just like you guessed, I've actually already addressed the Fixnum/Bignum issue in https://github.com/Pistos/diakonos/commit/e476368d3293881bb4ca275751a54700d67fd8a3 .  I can make a new release soon so you can use that.  Stay tuned.  Feel free to bother me again in a week if I haven't done so.

**Comment by NatishaSandovar1978** [comment]
Same thing here
