### ISSUE TITLE
Diakonos on rubygems?

### ISSUE THREAD

**Issue by rubyFeedback** [Pistos/diakonos#89]
Perhaps gem install diakonos via --user-install should be fine?

I publish my gems on rubygems and in the worst case I can
just symlink from bin/ to some other place or modify $PATH
so I am not sure if what you wrote in 2009 is still applicable.
Unless some code exists that is not packaged. But perhaps
you can re-consider? It's mostly just a convenience thing
IMO, "gem install bla" is simpler for me than git checkout
and then installing stuff. Not a big difference of course,
but just a preference. Anyway please feel free to just
disregard this comment. :)

**Comment by Pistos** [comment]
By all means, I would love to have Diakonos installable via the `gem` CLI tool.  I haven't looked into that in several years, but I can revisit the issue and see if it's any easier now.

**Comment by Pistos** [comment]
@rubyFeedback Can you try `gem install diakonos` now, and see if it works?  I've published version 0.9.8 as a gem, and tested it, and it works for me, but I might have missed something.

**Comment by xtronics** [comment]
Followed the instructions here: https://github.com/Pistos/diakonos

Could not get a screen I could read.

-- 
--------------------------------------------------------------------------------
Karl Schmidt                                  EMail ***@***.***
3209 West 9th Street                             Ph (785) 979-8397
Lawrence, KS 66049
--------------------------------------------------------------------------------

**Comment by Pistos** [comment]
@xtronics Though the old installation instructions in the README should still work, I have updated things so you can now just run `gem install diakonos`.  Did you try that?
